### PR TITLE
Allow a specific color and activeColor for every item

### PR DESCRIPTION
**Pull request by davystrong**
Added two new properties: colors and activeColors. Both properties are lists. If unset, defaults to the original color.
I modified this because it was something I needed. If you think this isn't right for the main repo, no problem!

### CODE REVIEW

**Comment by dadav** [comment]
Haha, I did the same thing. Is this repo unmaintained?

**Comment by Pyozer** [comment]
@dadav Hi, not many time to maintain my repos, it's not the only one to maintain ^^
I first take time for my package introduction_screen, but I will try to maintain this repo also.
This weekend or next week I should have some time.

**Comment by Pyozer** [comment]
@dadav Would you made a PR to apply your changes about shape indexed ? I checked your commits and seem good to merge ;)
I merge this PR firstly.
Thank you @davystrong, sorry for long time :/

**Comment by Pyozer** [comment]
Edit: I merged the PR, made some edit. I also take your shape indexed idea. Add use same logic for size param (sizes and activeSizes)

**Pull request merged**
